" set exrc
" set number
" set relativenumber
" set nohlsearch
" set hidden
" set noerrorbells
" set tabstop=4 softtabstop=4
" set shiftwidth=4
" set expandtab
" set smartindent
" set nowrap
" set noswapfile
" set nobackup
" set undodir=~/.vim/undodir
" set undofile
" set incsearch
" set scrolloff=10
" set colorcolumn=80
" set signcolumn=yes
