local icons = {}

icons.LSP_COMPLETION_ITEM_KIND_ICONS = {
   Text             = "",
   Method           = "",
   Function         = "",
   Constructor      = "⌘",
   Field            = "ﰠ",
   Variable         = "",
   Class            = "ﴯ",
   Interface        = "",
   Module           = "",
   Property         = "ﰠ",
   Unit             = "",
   Value            = "",
   Enum             = "",
   Keyword          = "",
   Snippet          = "",
   Color            = "",
   File             = "",
   Reference        = "",
   Folder           = "",
   EnumMember       = "",
   Constant         = "",
   Struct           = "ﳤ",
   Event            = "",
   Operator         = "",
   TypeParameter    = "",
}

-- Nerd Font icons for LSP symbol item kinds.
icons.LSP_SYMBOL_KIND_ICONS = {
   File             = "",
   Module           = "",
   Namespace        = ":",
   Package          = "",
   Class            = "ﴯ",
   Method           = "",
   Property         = "ﰠ",
   Field            = "ﰠ",
   Constructor      = "⌘",
   Enum             = "",
   Interface        = "",
   Function         = "",
   Variable         = "",
   Constant         = "",
   String           = "",
   Number           = "#",
   Boolean          = "",
   Array            = "",
   Object           = "",
   Key              = "",
   Null             = "␀",
   EnumMember       = "",
   Struct           = "ﳤ",
   Event            = "",
   Operator         = "",
   TypeParameter    = "",
}

return icons
